### ISSUE TITLE
Code a way to update the local storage of previous visitors.

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/catphotoapp#34]
More cats needed and code a way to update the local storage of previous visitors.

**Comment by Bouncey** [comment]
#60

**Comment by atjonathan** [comment]
@Bouncey, #60 is to expand the list of cats in the array. This issue is for setting up a way for us to update the users local storage. I've nearly finished fixing this issue. Should have a fix up by tomorrow at the latest 😃
